[build]
builder = "nixpacks"

[env]
NIXPACKS_INSTALL_CMD = "npm install"

[deploy]
startCommand = "npm start"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[healthcheck]
path = "/api/health"
timeout = 100
interval = 300
